Repository AcademySoftwareFoundation/rez, pull requests merged in 2019-06, with the labels that each got.

#647 Fix #558
  src/rezplugins/shell/cmd.py
Labels: topic:windows

#607 Bugfix for alias() on Windows
  src/rezplugins/shell/cmd.py
Labels: topic:windows

#497 Fix escaping backslashes in tcsh on Mac OS
  src/rezplugins/shell/tcsh.py
Labels: topic:osx

#622 Support for external PyYAML and Python 3
  src/rez/vendor/yaml/__init__.py
Labels: topic:py3

#602 [WIP] Feature/pip install modern
  src/rez/pip.py
Labels: topic:py-packaging
