Repository AcademySoftwareFoundation/rez, pull requests merged in 2019-09, with the labels that each got.

#712 very small py3 compat changes
  src/rez/cli/_main.py
  src/rez/rex.py
  src/rez/utils/scope.py
Labels: topic:py3

#713 .next() to next()
  src/rez/build_system.py
  src/rez/package_maker__.py
  src/rez/package_order.py
  src/rez/package_py_utils.py
  src/rez/package_search.py
  src/rez/packages_.py
  src/rez/resolved_context.py
  src/rez/rex.py
  src/rez/shells.py
  src/rez/solver.py
  src/rez/status.py
  src/rez/suite.py
  src/rez/system.py
  src/rez/tests/test_copy_package.py
  src/rez/tests/test_packages.py
  src/rez/wrapper.py
  src/rezplugins/package_repository/filesystem.py
Labels: topic:py3

#714 yaml upgrade
  src/rez/cli/_bez.py
  src/rez/cli/forward.py
  src/rez/config.py
  src/rez/resolved_context.py
  src/rez/serialise.py
  src/rez/suite.py
  src/rez/tests/test_release.py
  src/rez/utils/yaml.py
  src/rez/vendor/README.md
  src/rez/vendor/yaml/__init__.py
  src/rez/vendor/yaml/lib/__init__.py
  src/rez/vendor/yaml/lib/composer.py
  src/rez/vendor/yaml/lib/constructor.py
  src/rez/vendor/yaml/lib/cyaml.py
  src/rez/vendor/yaml/lib/dumper.py
  src/rez/vendor/yaml/lib/emitter.py
  src/rez/vendor/yaml/lib/error.py
  src/rez/vendor/yaml/lib/events.py
  src/rez/vendor/yaml/lib/loader.py
  src/rez/vendor/yaml/lib/nodes.py
  src/rez/vendor/yaml/lib/parser.py
  src/rez/vendor/yaml/lib/reader.py
  src/rez/vendor/yaml/lib/representer.py
  src/rez/vendor/yaml/lib/resolver.py
  src/rez/vendor/yaml/lib/scanner.py
  src/rez/vendor/yaml/lib/serializer.py
  src/rez/vendor/yaml/lib/tokens.py
  src/rez/vendor/yaml/lib3/__init__.py
  src/rez/vendor/yaml/lib3/composer.py
  src/rez/vendor/yaml/lib3/constructor.py
  src/rez/vendor/yaml/lib3/cyaml.py
  src/rez/vendor/yaml/lib3/dumper.py
  src/rez/vendor/yaml/lib3/emitter.py
  src/rez/vendor/yaml/lib3/error.py
  src/rez/vendor/yaml/lib3/events.py
  src/rez/vendor/yaml/lib3/loader.py
  src/rez/vendor/yaml/lib3/nodes.py
  src/rez/vendor/yaml/lib3/parser.py
  src/rez/vendor/yaml/lib3/reader.py
  src/rez/vendor/yaml/lib3/representer.py
  src/rez/vendor/yaml/lib3/resolver.py
  src/rez/vendor/yaml/lib3/scanner.py
  src/rez/vendor/yaml/lib3/serializer.py
  src/rez/vendor/yaml/lib3/tokens.py
  src/rez/wrapper.py
  src/rezgui/objects/App.py
  src/rezgui/widgets/ContextSettingsWidget.py
  src/rezplugins/release_vcs/stub.py
Labels: topic:py3

#715 improve non-string iterable handling
  src/rez/resolved_context.py
  src/rez/rex.py
  src/rez/shells.py
  src/rez/util.py
Labels: topic:py3

#716 replace async with block to avoid py3 async keyword
  src/rez/resolved_context.py
  src/rez/utils/amqp.py
Labels: topic:py3

#717 import queue module through six
  src/rez/utils/amqp.py
Labels: topic:py3

#718 swap 2.6 support for 3.x in version module
  src/rez/vendor/version/util.py
  src/rez/vendor/version/version.py
Labels: topic:py3

#721 pull basestring from six.string_types - py2 gets basestring, py3 gets str
  src/rez/bind/_utils.py
  src/rez/cli/forward.py
  src/rez/config.py
  src/rez/developer_package.py
  src/rez/package_copy.py
  src/rez/package_filter.py
  src/rez/package_help.py
  src/rez/package_maker__.py
  src/rez/package_py_utils.py
  src/rez/package_resources_.py
  src/rez/package_serialise.py
  src/rez/package_test.py
  src/rez/packages_.py
  src/rez/plugin_managers.py
  src/rez/resolved_context.py
  src/rez/rex.py
  src/rez/shells.py
  src/rez/suite.py
  src/rez/tests/test_resources_.py
  src/rez/tests/test_shells.py
  src/rez/utils/data_utils.py
  src/rez/utils/filesystem.py
  src/rez/utils/graph_utils.py
  src/rez/utils/memcached.py
  src/rez/utils/schema.py
  src/rezgui/widgets/ContextSettingsWidget.py
  src/rezplugins/build_system/cmake.py
  src/rezplugins/build_system/custom.py
  src/rezplugins/package_repository/filesystem.py
  src/rezplugins/release_hook/amqp.py
  src/rezplugins/release_hook/command.py
  src/rezplugins/release_hook/emailer.py
  src/rezplugins/shell/cmd.py
Labels: topic:py3

#722 import StringIO from six.moves
  src/rez/serialise.py
  src/rez/tests/util.py
Labels: topic:py3

#723 update vendored colorama from 0.3.1 to 0.4.1
  src/rez/vendor/README.md
  src/rez/vendor/colorama/__init__.py
  src/rez/vendor/colorama/ansi.py
  src/rez/vendor/colorama/ansitowin32.py
  src/rez/vendor/colorama/initialise.py
  src/rez/vendor/colorama/tests/__init__.py
  src/rez/vendor/colorama/tests/ansi_test.py
  src/rez/vendor/colorama/tests/ansitowin32_test.py
  src/rez/vendor/colorama/tests/initialise_test.py
  src/rez/vendor/colorama/tests/isatty_test.py
  src/rez/vendor/colorama/tests/utils.py
  src/rez/vendor/colorama/tests/winterm_test.py
  src/rez/vendor/colorama/win32.py
  src/rez/vendor/colorama/winterm.py
Labels: topic:py3

#724 update vendored memcache from 1.5.3 to 1.5.9
  src/rez/vendor/README.md
  src/rez/vendor/memcache/memcache.py
Labels: topic:py3

#725 make Version properly iterable in py3
  src/rez/vendor/version/version.py
Labels: topic:py3

#727 modernize function manipulations and attrs
  src/rez/build_process_.py
  src/rez/release_hook.py
  src/rez/rex.py
  src/rez/serialise.py
Labels: topic:py3

#728 update imports in vendored pydot for py3
  src/rez/vendor/README.md
  src/rez/vendor/pydot/README
  src/rez/vendor/pydot/dot_parser.py
  src/rez/vendor/pydot/pydot.py
Labels: topic:py3

#729 update vendored schema for py3
  src/rez/vendor/schema/schema.py
  src/rez/vendor/schema/test_schema.py
Labels: topic:py3

#741 fix metaclass usage in example code
  src/rez/utils/data_utils.py
Labels: topic:py3

#740 address py3.8 deprecation of collections direct ABC access
  src/rez/util.py
Labels: topic:py3

#738 Vendor readme
  src/rez/vendor/README.md
Labels: documentation

#745 address #744 (rex dictmixin issue)
  src/rez/rex.py
  src/rez/utils/scope.py
Labels: bug, topic:py3
