Repository AcademySoftwareFoundation/rez, pull requests merged in 2022-02, with the labels that each got.

#1232 Re-enable py3 workflow in windows.yaml
  .github/workflows/windows.yaml
Labels: topic:windows

#1235 fix: address zsh install message displaying wrong completion script
  install.py
Labels: bug

#1199 Implement #1196
  src/rezplugins/shell/_utils/powershell_base.py
Labels: bug, topic:windows
