Repository AcademySoftwareFoundation/rez, pull requests merged in 2022-11, with the labels that each got.

#1391 Clarify when the commands block is executed during rez-build
  wiki/pages/Building-Packages.md
  wiki/pages/Package-Commands.md
  wiki/pages/Package-Definition-Guide.md
Labels: documentation

#1285 Fix 1255-possible-regression-appendenv-in-powershell-fails-if-env-variable-does-not-exist-already
  src/rezplugins/shell/_utils/powershell_base.py
Labels: bug, topic:windows

#1392 GOVERNANCE.md
  GOVERNANCE.md
Labels: ASWF
