Repository AcademySoftwareFoundation/rez, pull requests merged in 2023-11, with the labels that each got.

#1580 Fix sphinx warnings and show inheritance in API docs
  docs/source/conf.py
  src/rez/build_system.py
  src/rez/package_cache.py
  src/rez/package_copy.py
  src/rez/package_filter.py
  src/rez/package_maker.py
  src/rez/package_order.py
  src/rez/package_py_utils.py
  src/rez/package_remove.py
  src/rez/package_repository.py
  src/rez/package_resources.py
  src/rez/package_search.py
  src/rez/package_serialise.py
  src/rez/package_test.py
  src/rez/packages.py
  src/rez/plugin_managers.py
  src/rez/release_vcs.py
  src/rez/resolved_context.py
  src/rez/rex.py
  src/rez/rex_bindings.py
  src/rez/serialise.py
  src/rez/shells.py
  src/rez/solver.py
  src/rez/suite.py
  src/rez/utils/colorize.py
  src/rez/utils/data_utils.py
  src/rez/utils/execution.py
  src/rez/utils/filesystem.py
  src/rez/utils/logging_.py
  src/rez/utils/memcached.py
  src/rez/utils/pip.py
  src/rez/utils/platform_mapped.py
  src/rez/utils/py_dist.py
  src/rez/utils/resources.py
  src/rez/utils/schema.py
Labels: documentation

#1550 Continue on missing variant packages
  src/rez/config.py
  src/rez/data/tests/solver/packages/missing_variant_requires/1/package.py
  src/rez/rezconfig.py
  src/rez/solver.py
  src/rez/tests/test_completion.py
  src/rez/tests/test_packages.py
  src/rez/tests/test_solver.py
Labels: enhancement

#1590 Run benchmarks on Python 3.7 only since we can't install rez with 2.7
  .github/workflows/benchmark.yaml
Labels: run-benchmarks

#1599 Disable the commit of benchmarks on every release
  .github/workflows/benchmark.yaml
Labels: run-benchmarks
