Repository AcademySoftwareFoundation/rez, pull requests merged in 2024-03, with the labels that each got.

#1634 Cleanup backports since we are now Python 3.x+ only
  src/rez/backport/__init__.py
  src/rez/backport/importlib.py
  src/rez/backport/lru_cache.py
  src/rez/backport/ordereddict.py
  src/rez/backport/zipfile.py
  src/rez/cli/complete.py
  src/rez/cli/forward.py
  src/rez/config.py
  src/rez/plugin_managers.py
  src/rez/utils/resources.py
  src/rezplugins/package_repository/filesystem.py
Labels: run-benchmarks

#1633 Add development environment docs
  CONTRIBUTING.md
Labels: documentation

#1682 Improve explicitness of help doc of --command on rez-env
  src/rez/cli/env.py
Labels: enhancement, documentation, shell

#1691 Tick off several completed boxes in onboarding document
  ASWF/ONBOARDING.md
Labels: documentation, ASWF

#1672 Add -e/--editable flag to install script to create an editable install
  install.py
Labels: enhancement

#1689 Add releasing packages documentation
  docs/README.md
  docs/source/index.rst
  docs/source/releasing_packages.rst
  src/rez/rezconfig.py
Labels: documentation

#1677 Improve clarify of early binding functions documentation
  docs/source/building_packages.rst
  docs/source/environment.rst
  docs/source/package_definition.rst
Labels: documentation
