Repository AcademySoftwareFoundation/rez, pull requests merged in 2024-02, with the labels that each got.

#1627 Release 3.0.0
  CHANGELOG.md
  README.md
  src/rez/utils/_version.py
Labels: run-benchmarks

#1645 Add support for virtualenv in installer
  .github/workflows/installation.yaml
  .github/workflows/tests.yaml
  install.py
Labels: enhancement

#1660 Improve install docs by mentioning how to actually download rez
  docs/source/installation.rst
Labels: documentation
